exports.up = (knex, Promise) =>
  knex.schema.createTable('inquiries', (table) => {
    table.increments('id')
    table.text('question')
    table.text('mentor_notes')
    table.boolean('is_resolved')
    table.timestamps()
    table.integer('student_id')
      .unsigned().index().nullable()
      .references('id').inTable('students')
      .onDelete('SET NULL')
      .onUpdate('CASCADE')
    table.integer('mentor_id')
      .unsigned().index().nullable()
      .references('id').inTable('mentors')
      .onDelete('SET NULL')
      .onUpdate('CASCADE')
    table.integer('skill_id')
      .unsigned().index().nullable()
      .references('id').inTable('skills')
      .onDelete('SET NULL')
      .onUpdate('CASCADE')
  })

exports.down = (knex, Promise) =>
  knex.schema.dropTable('inquiries')
