scalar Date

enum InquiryStatus {
  UNRESOLVED
  RESOLVED  
}

enum SurveyQuestionType {
  TEXT
  CHOICE
}

"""
Object Type Definition
"""

type Technology {
  id: ID!
  name: String
  doc_link: String
  help_text: String
  projects: [Project]
  hackathons: [Hackathon]
}

type Project {
  id: ID!
  name: String!
  description: String
  tech_name: String
  students: [Student]
  hackathon: Hackathon
  technologies: [Technology]
}

type Session {
  id: ID!
  name: String!
  description: String
  time: String
  day: String
  place: String
  attendance: Int
  hackathon: Hackathon
}

type Student {
  id: ID!
  name: String
  email: String
  phone: String
  azurecode: Azurecode
  project: Project
  inquiries: [Inquiry]
}

type Azurecode {
  id: ID!
  code: String!
  expires_on: Date
  is_taken: Boolean
  student: Student
  hackathon: Hackathon
}

type Hackathon {
  id: ID!
  name: String
  slug: String
  description: String
  start_date: Date
  end_date: Date
  bot_deployed: String
  bot_directline_key: String
  survey_link: String
  survey_promo: String
  survey_prize: String
  technologies: [Technology]
  azurecodes: [Azurecode]
  mentors: [Mentor]
  projects: [Project]
  sessions: [Session]
  findStudent(email: String): Student
  students: [Student]
  inquiries: [Inquiry]
  surveys: [Survey]
  survey_submissions: [SurveySubmission]
}

type Mentor {
  id: ID!
  first_name: String
  last_name: String
  email: String
  phone: String
  bio: String
  is_available: Boolean
  skills: [Skill]
  hackathons: [Hackathon]
}

type Inquiry {
  id: ID!
  question: String
  mentor_notes: String
  is_resolved: Boolean
  created_at: String
  updated_at: String
  student: Student
  mentor: Mentor
  skill: Skill
}

type Skill {
  id: ID!
  name: String
  mentors: [Mentor]
  inquiries: [Inquiry]
}

type Survey {
  id: ID!
  title: String
  prize: String
  link: String
  promo: String
  survey_questions: [SurveyQuestion]
  hackathons: [Hackathon]
}

type SurveyQuestion {
  id: ID!
  prompt: String
  type: SurveyQuestionType
  survey: Survey
  order: Int
  survey_choices: [SurveyChoice]
}

type SurveyChoice {
  id: ID!
  value: String
  order: Int
  survey_question: SurveyQuestion
  survey_answers: [SurveyAnswer]
}

type SurveyAnswer {
  id: ID!
  survey_question: SurveyQuestion
  value: String
  survey_choice: SurveyChoice
  survey_submission: SurveySubmission
}

type SurveySubmission {
  id: ID!
  hackathon: Hackathon,
  survey: Survey,
  student: Student,
  survey_answers: SurveyAnswer
}

"""
Query Type Definition
"""

type Query {
  project(id: ID!): Project
  hackathons: [Hackathon]
  hackathon(id: ID!): Hackathon
  mentor(id: ID!): Mentor
  inquiry(id: ID!): Inquiry
  skill(id: ID!): Skill
  technology(id: ID!): Technology
  azurecode(id: ID!): Azurecode
  student(id: ID!): Student
  survey(id: ID!): Survey
  surveySubmission(id: ID!): SurveySubmission
  randomSubmission(hackathonId: ID!, surveyId: ID!): SurveySubmission
}

type Mutation {
  setInquiryStatus(id: ID!, status: InquiryStatus!): Inquiry
  setInquiryNotes(id: ID!, notes: String): Inquiry
  setInquiryMentor(inquiryId: ID!, mentorId: ID!): Inquiry
  issueAzurecodeById(id: ID!): Azurecode
  issueUnclaimedAzurecode(hackathonId: ID!, studentName:String!, studentEmail: String!, projectName: String!, projectDescription: String, projectTechText: String): Azurecode
  newInquiry(hackathonId: ID!, studentName: String!, studentEmail: String!, question: String!): Inquiry
  newStudentProject(hackathonId: ID!, projectName:String!, projectDescription: String, studentName: String!, studentEmail: String!, studentPhone: String): Project
}
